const { executeQuery } = require('./db');

async function runMigration() {
  console.log('Yeni cədvəllərin migrasiyası başladı...');

  const statements = [
    // 1. odenis_metodlari
    {
      name: 'odenis_metodlari cədvəli',
      sql: `
        CREATE TABLE odenis_metodlari (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          istifadeci_id NUMBER NOT NULL,
          ad VARCHAR2(100) NOT NULL,
          kart_tipi VARCHAR2(50) NOT NULL,
          son_dord_reqem VARCHAR2(4),
          kart_istifade_tarixi VARCHAR2(10),
          status VARCHAR2(20) DEFAULT 'active',
          FOREIGN KEY (istifadeci_id) REFERENCES istifadeciler(id) ON DELETE CASCADE
        )
      `,
      ignoreErrorCode: 'ORA-00955' // name is already used by an existing object
    },
    // 2. abunelik_xidmetleri
    {
      name: 'abunelik_xidmetleri cədvəli',
      sql: `
        CREATE TABLE abunelik_xidmetleri (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ad VARCHAR2(100) UNIQUE NOT NULL,
          logo_url VARCHAR2(500),
          vebsayt VARCHAR2(200),
          kateqoriya VARCHAR2(50)
        )
      `,
      ignoreErrorCode: 'ORA-00955'
    },
    // 3. xidmet_paketleri
    {
      name: 'xidmet_paketleri cədvəli',
      sql: `
        CREATE TABLE xidmet_paketleri (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          xidmet_id NUMBER NOT NULL,
          paket_adi VARCHAR2(100) NOT NULL,
          qiymet NUMBER(10, 2) NOT NULL,
          valyuta VARCHAR2(10) DEFAULT 'AZN',
          tezlik VARCHAR2(20) DEFAULT 'monthly',
          FOREIGN KEY (xidmet_id) REFERENCES abunelik_xidmetleri(id) ON DELETE CASCADE
        )
      `,
      ignoreErrorCode: 'ORA-00955'
    },
    // 4. abunelik_ortaqlar
    {
      name: 'abunelik_ortaqlar cədvəli',
      sql: `
        CREATE TABLE abunelik_ortaqlar (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          abunelik_id NUMBER NOT NULL,
          istifadeci_id NUMBER NOT NULL,
          ortaq_istifadeci_id NUMBER NOT NULL,
          pay_faizi NUMBER(5, 2) DEFAULT 50.00,
          status VARCHAR2(20) DEFAULT 'pending',
          FOREIGN KEY (abunelik_id) REFERENCES abunelikler(id) ON DELETE CASCADE,
          FOREIGN KEY (istifadeci_id) REFERENCES istifadeciler(id) ON DELETE CASCADE,
          FOREIGN KEY (ortaq_istifadeci_id) REFERENCES istifadeciler(id) ON DELETE CASCADE
        )
      `,
      ignoreErrorCode: 'ORA-00955'
    },
    // 5. budceler
    {
      name: 'budceler cədvəli',
      sql: `
        CREATE TABLE budceler (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          istifadeci_id NUMBER NOT NULL,
          limit_mebleq NUMBER(10, 2) NOT NULL,
          valyuta VARCHAR2(10) DEFAULT 'AZN',
          bildiris_faizi NUMBER(5, 2) DEFAULT 90.00,
          FOREIGN KEY (istifadeci_id) REFERENCES istifadeciler(id) ON DELETE CASCADE
        )
      `,
      ignoreErrorCode: 'ORA-00955'
    },
    // 6. istifadeci_ayarlari
    {
      name: 'istifadeci_ayarlari cədvəli',
      sql: `
        CREATE TABLE istifadeci_ayarlari (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          istifadeci_id NUMBER UNIQUE NOT NULL,
          esas_valyuta VARCHAR2(10) DEFAULT 'AZN',
          bildiris_metodu VARCHAR2(50) DEFAULT 'email',
          dil VARCHAR2(5) DEFAULT 'az',
          tema VARCHAR2(10) DEFAULT 'dark',
          FOREIGN KEY (istifadeci_id) REFERENCES istifadeciler(id) ON DELETE CASCADE
        )
      `,
      ignoreErrorCode: 'ORA-00955'
    },
    // 7. ALTER TABLE abunelikler ADD odenis_metodu_id
    {
      name: 'abunelikler cədvəlinə odenis_metodu_id əlavə etmək',
      sql: `
        ALTER TABLE abunelikler ADD odenis_metodu_id NUMBER
      `,
      ignoreErrorCode: 'ORA-01430' // column being added already exists in table
    },
    // 8. ALTER TABLE abunelikler ADD CONSTRAINT fk_abunelik_odenis_metodu
    {
      name: 'abunelikler cədvəlinə odenis_metodu foreign key əlavə etmək',
      sql: `
        ALTER TABLE abunelikler 
        ADD CONSTRAINT fk_abunelik_odenis_metodu 
        FOREIGN KEY (odenis_metodu_id) 
        REFERENCES odenis_metodlari(id) 
        ON DELETE SET NULL
      `,
      ignoreErrorCode: 'ORA-02275' // referential constraint already exists
    }
  ];

  for (const stmt of statements) {
    try {
      await executeQuery(stmt.sql);
      console.log(`[UĞURLU] ${stmt.name} yaradıldı/tətbiq edildi.`);
    } catch (e) {
      if (e.message && (e.message.includes(stmt.ignoreErrorCode) || e.message.includes('already exists') || e.message.includes('already indexed') || e.message.includes('already has'))) {
        console.log(`[MÖVCUDDUR] ${stmt.name} artıq mövcuddur, keçirilir.`);
      } else {
        console.error(`[XƏTA] ${stmt.name} zamanı xəta baş verdi:`, e.message);
      }
    }
  }

  console.log('Migrasiya tamamlandı!');
}

runMigration();
