-- 1. ISTIFADECILER (Users) Table
CREATE TABLE istifadeciler (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    yaradilma_tarixi TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. ABUNELIKLER (Subscriptions) Table
CREATE TABLE abunelikler (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    istifadeci_id NUMBER NOT NULL,
    ad VARCHAR2(100) NOT NULL,
    qiymet NUMBER(10, 2) NOT NULL,
    valyuta VARCHAR2(10) DEFAULT 'AZN',
    odenis_tezliyi VARCHAR2(20) DEFAULT 'monthly',
    baslama_tarixi DATE NOT NULL,
    novbeti_odenis_tarixi DATE NOT NULL,
    kateqoriya VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'active',
    yaradilma_tarixi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (istifadeci_id) REFERENCES istifadeciler(id) ON DELETE CASCADE
);

-- 3. BILDIRISLER (Notifications) Table
CREATE TABLE bildirisler (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    istifadeci_id NUMBER NOT NULL,
    basliq VARCHAR2(200) NOT NULL,
    mesaj VARCHAR2(1000) NOT NULL,
    gonderilme_tarixi DATE DEFAULT SYSDATE,
    oxunub NUMBER(1) DEFAULT 0,
    FOREIGN KEY (istifadeci_id) REFERENCES istifadeciler(id) ON DELETE CASCADE
);

-- 4. ODENIS_TARIXCESI (Payment History) Table
CREATE TABLE odenis_tarixcesi (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abunelik_id NUMBER NOT NULL,
    istifadeci_id NUMBER NOT NULL,
    odenis_tarixi DATE NOT NULL,
    mebleq NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'success',
    FOREIGN KEY (abunelik_id) REFERENCES abunelikler(id) ON DELETE CASCADE,
    FOREIGN KEY (istifadeci_id) REFERENCES istifadeciler(id) ON DELETE CASCADE
);

-- Test ucun hazir (seed) melumatlar
INSERT INTO istifadeciler (ad, email) VALUES ('Abbas Abbasov', 'abbas@example.com');
INSERT INTO istifadeciler (ad, email) VALUES ('Elnur Mammadov', 'elnur@example.com');

INSERT INTO abunelikler (istifadeci_id, ad, qiymet, valyuta, odenis_tezliyi, baslama_tarixi, novbeti_odenis_tarixi, kateqoriya, status)
VALUES (1, 'Netflix', 12.99, 'USD', 'monthly', TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), 'Entertainment', 'active');

INSERT INTO abunelikler (istifadeci_id, ad, qiymet, valyuta, odenis_tezliyi, baslama_tarixi, novbeti_odenis_tarixi, kateqoriya, status)
VALUES (2, 'Spotify', 4.99, 'USD', 'monthly', TO_DATE('2026-02-15', 'YYYY-MM-DD'), TO_DATE('2026-08-15', 'YYYY-MM-DD'), 'Music', 'active');

INSERT INTO bildirisler (istifadeci_id, basliq, mesaj)
VALUES (1, 'Yaxınlaşan Ödəniş', 'Netflix abunəliyiniz növbəti ay üçün yenilənəcək.');

INSERT INTO odenis_tarixcesi (abunelik_id, odenis_tarixi, mebleq, status)
VALUES (1, TO_DATE('2026-01-01', 'YYYY-MM-DD'), 12.99, 'success');

COMMIT;
